/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import java.awt.Event;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JMenuItem;

/**
 *
 * @author Nadja
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuReservations = new javax.swing.JMenu();
        jmiSeeAllReservations = new javax.swing.JMenuItem();
        jmiMakeReservation = new javax.swing.JMenuItem();
        jMenuClients = new javax.swing.JMenu();
        jmiSeeAllClients = new javax.swing.JMenuItem();
        jmiAddNewClient = new javax.swing.JMenuItem();
        JMenuPservice = new javax.swing.JMenu();
        jmiSeeAllServices = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUser.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        lblUser.setText("n");

        btnLogout.setBackground(new java.awt.Color(255, 102, 102));
        btnLogout.setText("Logout");

        jMenuReservations.setText("Reservations");

        jmiSeeAllReservations.setText("See all reservations");
        jMenuReservations.add(jmiSeeAllReservations);

        jmiMakeReservation.setText("Make a reservation");
        jMenuReservations.add(jmiMakeReservation);

        jMenuBar1.add(jMenuReservations);

        jMenuClients.setText("Clients");

        jmiSeeAllClients.setText("See all clients");
        jMenuClients.add(jmiSeeAllClients);

        jmiAddNewClient.setText("Add new client");
        jMenuClients.add(jmiAddNewClient);

        jMenuBar1.add(jMenuClients);

        JMenuPservice.setText("Photography services");

        jmiSeeAllServices.setText("See all services");
        JMenuPservice.add(jmiSeeAllServices);

        jMenuBar1.add(JMenuPservice);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(lblUser)
                .addGap(43, 43, 43)
                .addComponent(btnLogout)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuPservice;
    private javax.swing.JButton btnLogout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClients;
    private javax.swing.JMenu jMenuReservations;
    private javax.swing.JMenuItem jmiAddNewClient;
    private javax.swing.JMenuItem jmiMakeReservation;
    private javax.swing.JMenuItem jmiSeeAllClients;
    private javax.swing.JMenuItem jmiSeeAllReservations;
    private javax.swing.JMenuItem jmiSeeAllServices;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JMenu getJMenuPservice() {
        return JMenuPservice;
    }

    public void setJMenuPservice(javax.swing.JMenu JMenuPservice) {
        this.JMenuPservice = JMenuPservice;
    }

    public javax.swing.JMenu getjMenuClients() {
        return jMenuClients;
    }

    public void setjMenuClients(javax.swing.JMenu jMenuClients) {
        this.jMenuClients = jMenuClients;
    }

    public javax.swing.JMenu getjMenuReservations() {
        return jMenuReservations;
    }

    public void setjMenuReservations(javax.swing.JMenu jMenuReservations) {
        this.jMenuReservations = jMenuReservations;
    }

    public javax.swing.JMenuItem getJmiAddNewClient() {
        return jmiAddNewClient;
    }

    public void setJmiAddNewClient(javax.swing.JMenuItem jmiAddNewClient) {
        this.jmiAddNewClient = jmiAddNewClient;
    }

    public javax.swing.JMenuItem getJmiSeeAllClients() {
        return jmiSeeAllClients;
    }

    public void setJmiSeeAllClients(javax.swing.JMenuItem jmiSeeAllClients) {
        this.jmiSeeAllClients = jmiSeeAllClients;
    }

    public javax.swing.JMenuItem getJmiSeeAllReservations() {
        return jmiSeeAllReservations;
    }

    public void setJmiSeeAllReservations(javax.swing.JMenuItem jmiSeeAllReservations) {
        this.jmiSeeAllReservations = jmiSeeAllReservations;
    }

    public javax.swing.JMenuItem getJmiSeeAllServices() {
        return jmiSeeAllServices;
    }

    public void setJmiSeeAllServices(javax.swing.JMenuItem jmiSeeAllServices) {
        this.jmiSeeAllServices = jmiSeeAllServices;
    }

     public void addjmiAddNewClientListener(ActionListener actionListener) {
        jmiAddNewClient.addActionListener(actionListener);
    }

    public void addjmiSeeAllClientsListener(ActionListener actionListener) {
        jmiSeeAllClients.addActionListener(actionListener);
    }

    public void addjmiSeeAllReservationsListener(ActionListener actionListener) {
        jmiSeeAllReservations.addActionListener(actionListener);
    }

    public void addjmiSeeAllServicesListener(ActionListener actionListener) {
        jmiSeeAllServices.addActionListener(actionListener);
    }

    public JMenuItem getJmiMakeReservation() {
        return jmiMakeReservation;
    }

    public JLabel getLblUser() {
        return lblUser;
    }

    public void setLblUser(JLabel lblUser) {
        this.lblUser = lblUser;
    }
    public void addBtnLogoutActionListener(ActionListener ae){
        btnLogout.addActionListener(ae);
    }
    


}
